NIAD-127 Inbound Deduction Request Rejection Transaction
NHSDigital/integration-adaptor-nhais pull request #164
Opened 2020-07-15 13:05 UTC by mattd-kainos

2020-07-16 07:15 UTC, grzegorz-robak submitted a review, later dismissed

2020-07-16 11:57 UTC, grzegorz-robak approved these changes

2020-07-17 07:32 UTC, bartek-sarul commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/service/edifact_to_fhir/DeductionRejectionTransactionMapper.java
> +            .flatMap(FhirTransactionMapper::mapToNhsIdentifier)
The same optional comment as here
https://github.com/nhsconnect/integration-adaptor-nhais/pull/168/files#r456267417

2020-07-17 07:33 UTC, bartek-sarul commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/service/edifact_to_fhir/DeductionRejectionTransactionMapper.java
> +            .orElseThrow(() -> new EdifactValidationException("NHS Number is mandatory for inbound deduction request rejection"));
The `ifPresentOrElse` would be better IMO

2020-07-17 07:33 UTC, bartek-sarul commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/service/edifact_to_fhir/FP69FlagRemovalTransactionMapper.java
> +            .flatMap(FhirTransactionMapper::mapToNhsIdentifier)
The same optional comment as here
https://github.com/nhsconnect/integration-adaptor-nhais/pull/168/files#r456267417

2020-07-17 07:34 UTC, bartek-sarul requested changes
optional comments

2020-07-17 08:59 UTC, grzegorz-robak requested changes

2020-07-17 08:59 UTC, grzegorz-robak commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/service/edifact_to_fhir/FhirTransactionMapper.java
> +    }
This doesn't belong here. Use just `.map(NhsIdentifier::new)` instead of that

2020-07-17 10:03 UTC, grzegorz-robak approved these changes

2020-07-17 10:12 UTC, bartek-sarul approved these changes

2020-07-17 11:43 UTC, merged