NIAD-125: FPN FP69 HA to GP prior notification
NHSDigital/integration-adaptor-nhais pull request #169
Opened 2020-07-16 11:39 UTC by bartek-sarul

2020-07-16 12:26 UTC, grzegorz-robak requested changes

2020-07-16 12:26 UTC, grzegorz-robak commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/model/edifact/FP69ExpiryDate.java
> +    private @NonNull Instant timestamp;
Don't use `Instant` when `LocalDate` is enough

2020-07-16 12:26 UTC, grzegorz-robak commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/model/edifact/FP69ReasonCode.java
> +    private @NonNull Integer code;
Could be `final`

2020-07-16 13:54 UTC, grzegorz-robak submitted a review, later dismissed

2020-07-16 15:07 UTC, mattd-kainos commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/model/edifact/PersonAddress.java
> +    // NAD+PAT++:::ORPINGTON:'
stray comment?

2020-07-16 15:09 UTC, mattd-kainos commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/model/edifact/Segment.java
> +    public static <T> List<T> removeEmptyTrailingFields(List<T> list, Predicate<T> predicate) {
why public?

2020-07-16 15:39 UTC, mattd-kainos submitted a review, later dismissed

2020-07-17 07:03 UTC, bartek-sarul commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/model/edifact/Segment.java
> +    public static <T> List<T> removeEmptyTrailingFields(List<T> list, Predicate<T> predicate) {
ahh, a leftover while I was experimenting

2020-07-17 08:47 UTC, grzegorz-robak commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/service/edifact_to_fhir/FP69PriorNotificationTransactionMapper.java
> +            Optional.ofNullable(personAddress.getAddressLine5()))
These Optionals are redundant

2020-07-17 08:53 UTC, grzegorz-robak submitted a review, later dismissed

2020-07-17 09:28 UTC, mattd-kainos submitted a review, later dismissed

2020-07-17 09:44 UTC, grzegorz-robak commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/service/edifact_to_fhir/FP69PriorNotificationTransactionMapper.java
> +            Optional.ofNullable(personAddress.getAddressLine5()))
Ok, I was kind of wrong as `Stream.of()` doesn't support nulls, but... that would work:
````java
address.setLine(Stream.builder()
	.add(personAddress.getAddressLine1())
	.add(personAddress.getAddressLine2())
	.add(personAddress.getAddressLine3())
	.add(personAddress.getAddressLine4())
	.add(personAddress.getAddressLine5())
	.build()
	.map(NullableStringType::new)
    .map(StringType.class::cast)
    .collect(Collectors.toList()));
````

2020-07-17 10:17 UTC, Alicja-Kainos submitted a review, later dismissed

2020-07-17 13:19 UTC, grzegorz-robak approved these changes

2020-07-17 13:23 UTC, merged