NIAD-402: Using correct cipher in  NHS segment and added inbound UAT …
NHSDigital/integration-adaptor-nhais pull request #218
Opened 2020-08-10 08:44 UTC by grzegorz-robak

…RECEP tests

2020-08-10 09:36 UTC, jaroslaw-wojciechowski requested changes

2020-08-10 09:36 UTC, jaroslaw-wojciechowski commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/inbound/RecepProducerService.java
> +            return "9999"; //default if NAD+GP segment is missing in first transaction
should be static final

2020-08-10 09:36 UTC, jaroslaw-wojciechowski commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/model/edifact/Message.java
> +            .orElse("9999");
should be static final

2020-08-10 09:37 UTC, grzegorz-robak commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/inbound/RecepProducerService.java
> +            return "9999"; //default if NAD+GP segment is missing in first transaction
Just did that :)

2020-08-10 09:38 UTC, grzegorz-robak commented on src/main/java/uk/nhs/digital/nhsconnect/nhais/model/edifact/Message.java
> +            .orElse("9999");
git commit -m "Test fix"

2020-08-10 10:43 UTC, jaroslaw-wojciechowski approved these changes

2020-08-11 07:55 UTC, mattd-kainos approved these changes

2020-08-11 07:55 UTC, merged