[WIP] NIAD-148: create scaffold for HA/GP link adaptor service inbouns
NHSDigital/integration-adaptor-nhais pull request #29
Opened 2020-05-20 07:51 UTC by Alicja-Kainos

use of event(message) listener in proton_queue_adaptor (common library), sketch of incoming message processor (worker.py)

2020-05-20 07:52 UTC, Alicja-Kainos commented on main.py
> +    #temporary code, to be replaced by proper tests
the sending does not work now, this method is only for test/debug purposes and should be removed

2020-05-21 07:54 UTC, jaroslaw-wojciechowski submitted a review, later dismissed

2020-05-21 12:28 UTC, mattd-kainos commented on inbound/request/inbound_handler.py
> +            loop = asyncio.new_event_loop()
I'm concerned about this code creating and setting the event loop. set_event_loop is applied globally and will affect other parts of the application

2020-05-21 12:28 UTC, mattd-kainos requested changes
concerns over manual management of event loop

2020-05-22 08:40 UTC, mattd-kainos requested changes
just a basic integration test to demonstrate the inbound queues working correctly

2020-05-22 12:05 UTC, mattd-kainos commented on integration_tests/int_inbound_tests.py
> +        self.assertTrue(len(message.body) > 0, 'message from queue should not be empty')
what should the supplier_queue message body be exactly?

2020-05-25 07:56 UTC, michael-kainos commented on README.md
> +| NHAIS_DB_ENDPOINT_URL      |          | URL of dynamodb instance (if used)
as the variable does not now reference dynamodb should we update the description also to remove this?

2020-05-25 10:56 UTC, mattd-kainos approved these changes

2020-05-25 10:57 UTC, Broom94 approved these changes

2020-05-25 10:57 UTC, merged